<template>
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="margin-right:-1.6px;display:block;animation-play-state:paused"><rect x="8.5" y="8.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="29.5" y="8.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="50.5" y="8.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="71.5" y="8.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="8.5" y="29.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="71.5" y="29.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="8.5" y="50.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="71.5" y="50.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="8.5" y="71.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="29.5" y="71.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="50.5" y="71.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" />
    <rect x="71.5" y="71.5" width="20" height="20" fill="rgb(28, 69, 149)" style="animation-play-state:paused" /><!-- generated by https://loading.io/ --></svg>
</template>
